=== zigal0/NetCracker/SkillBench/javaXMLTasks/xPathCaller/emp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
        xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="ns:emp"
        xmlns:tns="ns:emp"
        elementFormDefault="qualified">
        <element name="content">
                <complexType>
                        <sequence>
                                <element ref="tns:emp"/>
                                <element ref="tns:dept"/>
                                <element ref="tns:salgrade"/>
                        </sequence>
                </complexType>
                <key name="empno-key">
                        <selector xpath="tns:emp/tns:employee"/>
                        <field xpath="@empno"/>
                </key>
                <keyref name="mgr-ref" refer="tns:empno-key">
                        <selector xpath="tns:emp/tns:employee"/>
                        <field xpath="@mgr"/>
                </keyref>
                <key name="deptno-key">
                        <selector xpath="tns:dept/tns:department"/>
                        <field xpath="@deptno"/>
                </key>
                <keyref name="deptno-ref" refer="tns:deptno-key">
                        <selector xpath="tns:emp/tns:employee"/>
                        <field xpath="@deptno"/>
                </keyref>
        </element>
        <element name="emp">
                <complexType>
                        <sequence>
                                <element name="employee" minOccurs="0" maxOccurs="unbounded">
                                        <complexType>
                                                <sequence>
                                                        <element name="ename" type="string"/>
                                                        <element name="job" type="string"/>
                                                        <element name="hiredate" type="date"/>
                                                        <element name="sal" type="decimal"/>
                                                        <element name="comm" type="decimal"/>
                                                </sequence>
                                                <attribute name="empno" type="positiveInteger" use="required"/>
                                                <attribute name="mgr" type="positiveInteger"/>
                                                <attribute name="deptno" type="positiveInteger" use="required"/>
                                        </complexType>
                                </element>
                        </sequence>
                </complexType>
        </element>
        <element name="dept">
                <complexType>
                        <sequence>
                                <element name="department" minOccurs="0" maxOccurs="unbounded">
                                        <complexType>
                                                <sequence>
                                                        <element name="dname" type="string"/>
                                                        <element name="loc" type="string"/>
                                                </sequence>
                                                <attribute name="deptno" type="positiveInteger" use="required"/>
                                        </complexType>
                                </element>
                        </sequence>
                </complexType>
        </element>
        <element name="salgrade">
                <complexType>
                        <sequence>
                                <element name="sal" minOccurs="0" maxOccurs="unbounded">
                                        <complexType>
                                                <sequence>
                                                        <element name="losal" type="string"/>
                                                        <element name="hisal" type="string"/>
                                                </sequence>
                                                <attribute name="grade" type="positiveInteger" use="required"/>
                                        </complexType>
                                </element>
                        </sequence>
                </complexType>
                <unique name="grade">
                        <selector xpath="tns:sal"/>
                        <field xpath="@grade"/>
                </unique>
        </element>
</schema>

=== zigal0/NetCracker/SkillBench/javaXMLTasks/xPathCaller/emp.xml
<?xml version="1.0" encoding="UTF-8"?>
<content
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="ns:emp"
        xsi:schemaLocation="ns:emp emp.xsd">
        <emp>
                <employee deptno="10" empno="7369" mgr="7902">
                        <ename>SMITH</ename>
                        <job>CLERK</job>
                        <hiredate>1980-12-17</hiredate>
                        <sal>800.00</sal>
                        <comm>0.0</comm>
                </employee>
                <employee deptno="30" empno="7499" mgr="7698">
                        <ename>ALLEN</ename>
                        <job>SALESMAN</job>
                        <hiredate>1981-02-20</hiredate>
                        <sal>1600.00</sal>
                        <comm>300.00</comm>
                </employee>
                <employee deptno="30" empno="7521" mgr="7698">
                        <ename>WARD</ename>
                        <job>SALESMAN</job>
                        <hiredate>1981-02-22</hiredate>
                        <sal>1250.00</sal>
                        <comm>500.00</comm>
                </employee>
                <employee deptno="20" empno="7566" mgr="7839">
                        <ename>JONES</ename>
                        <job>MANAGER</job>
                        <hiredate>1981-04-02</hiredate>
                        <sal>2975.00</sal>
                        <comm>0.0</comm>
                </employee>
                <employee deptno="30" empno="7654" mgr="7698">
                        <ename>MARTIN</ename>
                        <job>SALESMAN</job>
                        <hiredate>1981-09-28</hiredate>
                        <sal>1250.00</sal>
                        <comm>1400.00</comm>
                </employee>
                <employee deptno="30" empno="7698" mgr="7839">
                        <ename>BLAKE</ename>
                        <job>MANAGER</job>
                        <hiredate>1981-05-01</hiredate>
                        <sal>2850.00</sal>
                        <comm>0.0</comm>
                </employee>
                <employee deptno="10" empno="7782" mgr="7839">
                        <ename>CLARK</ename>
                        <job>MANAGER</job>
                        <hiredate>1981-06-09</hiredate>
                        <sal>2450.00</sal>
                        <comm>0.0</comm>
                </employee>
                <employee deptno="20" empno="7788" mgr="7566">
                        <ename>SCOTT</ename>
                        <job>ANALYST</job>
                        <hiredate>1982-12-09</hiredate>
                        <sal>3000.00</sal>
                        <comm>0.0</comm>
                </employee>
                <employee deptno="10" empno="7839">
                        <ename>KING</ename>
                        <job>PRESIDENT</job>
                        <hiredate>1981-11-17</hiredate>
                        <sal>5000.00</sal>
                        <comm>0.0</comm>
                </employee>
                <employee deptno="30" empno="7844" mgr="7698">
                        <ename>TURNER</ename>
                        <job>SALESMAN</job>
                        <hiredate>1981-09-08</hiredate>
                        <sal>1500.00</sal>
                        <comm>0.00</comm>
                </employee>
                <employee deptno="20" empno="7876" mgr="7788">
                        <ename>ADAMS</ename>
                        <job>CLERK</job>
                        <hiredate>1983-01-12</hiredate>
                        <sal>1100.00</sal>
                        <comm>0.0</comm>
                </employee>
                <employee deptno="30" empno="7900" mgr="7698">
                        <ename>JAMES</ename>
                        <job>CLERK</job>
                        <hiredate>1981-12-03</hiredate>
                        <sal>950.00</sal>
                        <comm>0.0</comm>
                </employee>
                <employee deptno="20" empno="7902" mgr="7566">
                        <ename>FORD</ename>
                        <job>ANALYST</job>
                        <hiredate>1981-12-03</hiredate>
                        <sal>3000.00</sal>
                        <comm>0.0</comm>
                </employee>
                <employee deptno="10" empno="7934" mgr="7782">
                        <ename>MILLER</ename>
                        <job>CLERK</job>
                        <hiredate>1982-01-23</hiredate>
                        <sal>1300.00</sal>
                        <comm>0.0</comm>
                </employee>
        </emp>
        <dept>
                <department deptno="10">
                        <dname>ACCOUNTING</dname>
                        <loc>NEW YORK</loc>
                </department>
                <department deptno="20">
                        <dname>RESEARCH</dname>
                        <loc>DALLAS</loc>
                </department>
                <department deptno="30">
                        <dname>SALES</dname>
                        <loc>CHICAGO</loc>
                </department>
                <department deptno="40">
                        <dname>OPERATIONS</dname>
                        <loc>BOSTON</loc>
                </department>
        </dept>
        <salgrade>
                <sal grade="1">
                        <losal>700</losal>
                        <hisal>1200</hisal>
                </sal>
                <sal grade="2">
                        <losal>1201</losal>
                        <hisal>1400</hisal>
                </sal>
                <sal grade="3">
                        <losal>1401</losal>
                        <hisal>2000</hisal>
                </sal>
                <sal grade="4">
                        <losal>2001</losal>
                        <hisal>3000</hisal>
                </sal>
                <sal grade="5">
                        <losal>3001</losal>
                        <hisal>9999</hisal>
                </sal>
        </salgrade>
</content>
